### ISSUE TITLE
How to use it in ASP.NET MVC 5

### ISSUE THREAD

**Issue by iSatishYadav** [ahydrax/Hangfire.Heartbeat#1]
The current readme says

### Install a package from Nuget.

Then add this in your code:

for service side:
````csharp
app.UseHangfireServer(additionalProcesses: new[] { new SystemMonitor() });
````
for dashboard:
````csharp
services.AddHangfire(configuration => configuration.UseHeartbeatPage());
````

Where do I add the second line ````services.AddHangfire(configuration => configuration.UseHeartbeatPage());```` in ASP.NET MVC 5 as (unlike ASP.NET Core) there is no ````ConfigureServices```` method.

**Comment by Shafeeq86** [comment]
Yes..please share the sample code

**Comment by gtmadev** [comment]
I ran into this as well. What I did was I placed all my configuration code in a Startup class (per docs when using ASP.NET MVC). My code is VB, but it is very easy to convert to C# as needed.

Here is my code in the Startup.vb class for setting up the monitoring service.

`Dim heartbeatService As IBackgroundProcess = New SystemMonitor(checkInterval:=TimeSpan.FromSeconds(1))`

Add that as an "additionalProcesses" parameter when calling UseHangfire()

`app.UseHangfireServer(serverOptions, heartbeatService)`

Next.. add your global configuration parameter for the dashboard in the Global.asax.vb (or C# version). Note: You will need to import (using) Hangfire.Heartbeat.

`With Hangfire.GlobalConfiguration.Configuration()
            .UseHeartbeatPage(New HeartbeatOptions(checkInterval:=TimeSpan.FromSeconds(1)))
        End With`

And that's it. The new page will now appear on your Dashboard with metrics coming in every second.

**Comment by Godaday** [comment]
@gtmadev good job  thanks I ran into this as well

**Comment by ellonia** [comment]
If you use [Making ASP.NET application always running](https://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html) in MVC, your settings will change to:

**HangfireBootstrapper.cs:**
 ```
public void Start()
{ 
      HostingEnvironment.RegisterObject(this);

      GlobalConfiguration.Configuration
          .UseSqlServerStorage("connection string");
          // Specify other options here

      var options = new BackgroundJobServerOptions {};

      IBackgroundProcess heartbeatService = new ProcessMonitor(TimeSpan.FromSeconds(1));
      _backgroundJobServer = new BackgroundJobServer(options, JobStorage.Current ,new IBackgroundProcess[]{ heartbeatService });
}
```

**Startup.cs (Example):**
```
public void Configuration(IAppBuilder app)
{
    GlobalConfiguration.Configuration.UseHeartbeatPage(TimeSpan.FromSeconds(1));
    GlobalJobFilters.Filters.Add(new ProlongExpirationTimeAttribute()); 

    app.UseHangfireDashboard("/jobs", new DashboardOptions()
    {
        Authorization = new[] { new HangFireAuthorizationFilter() }
    });            
}
```
![image](https://user-images.githubusercontent.com/49064914/76307038-15b79700-62d9-11ea-8a5a-660175a7162b.png)
