### ISSUE TITLE
SystemMonitor New Constructor for Multiple PID or Process[]

### ISSUE THREAD

**Issue by deaquino** [ahydrax/Hangfire.Heartbeat#2]
Would be great if SystemMonitor is not sealed and admit a list of PIDs or Process in order to monitor all of them.

**Comment by ahydrax** [comment]
Hi @deaquino,
Could you explain the case you're going to solve?
I need to figure out what and how extensions points can be added.

**Comment by deaquino** [comment]
Hi @ahydrax 
The current behavior (or what I achieved) is to have the current process chart of processor and memory consuming.

Would be great, that more processes could be tracked as well. Not just the current process.
Maybe there is another way to do that and I don´t know how.

Thanks!

**Comment by ahydrax** [comment]
@deaquino probably I can add constructor with `Process` parameter. Would that be enough?

**Comment by ahydrax** [comment]
Added in https://www.nuget.org/packages/Hangfire.Heartbeat/0.5.0
