### ISSUE TITLE
hangfire 1.7 error

### ISSUE THREAD

**Issue by zsy619** [ahydrax/Hangfire.Heartbeat#3]
Uncaught ReferenceError: Rickshaw is not defined
    at createGraph (jspage:97)
    at window.onload (jspage:176)
![1554027149241](https://user-images.githubusercontent.com/6278792/55287827-b7074f00-53e0-11e9-97ca-914273785d93.jpg)

**Comment by ahydrax** [comment]
Hi @zsy619 , thanks for report. 
From hf 1.7 release notes:
• Changed – Replace Rickshaw with Chart.js to have beautiful charts with less headache.
Currently, frontend relies on rickshaw so it will take a time to port the code.

**Comment by zsy619** [comment]
@ahydrax hello，When can it be revised?

**Comment by ahydrax** [comment]
@zsy619 fixed in https://www.nuget.org/packages/Hangfire.Heartbeat/0.4.0
