### ISSUE TITLE
JavaScript static scripts loading issue

### ISSUE THREAD

**Issue by dante2130** [ahydrax/Hangfire.Heartbeat#6]
~Hi. I worked on project with ASP.NET Core & ASP.NET Boilerplate. After loading Heartbeat module over Hangfire Dashboard - JavaScript static files won't be loaded in browser. because script files have incorrect MIME type i think. More details on screenshot. This prevent to loading page correctly - she is empty~

P.S. I found merged pull request which fixes this. But i using version from NuGet. Maybe make sense for doing release update?) Thanks in advance

<img width="754" alt="Screenshot 2019-06-27 at 13 42 58" src="https://user-images.githubusercontent.com/5721238/60260781-02979f00-98e3-11e9-999d-89f89341d218.png">

<img width="910" alt="Screenshot 2019-06-27 at 13 55 39" src="https://user-images.githubusercontent.com/5721238/60260909-4b4f5800-98e3-11e9-8451-8c4f54c7e868.png">

**Comment by ahydrax** [comment]
Closed by https://www.nuget.org/packages/Hangfire.Heartbeat/0.5.0

**Comment by dante2130** [comment]
In newest version on NuGet (0.5) mimetype is 'application/js'

**Comment by ahydrax** [comment]
Have you cleaned browser cache as it works for me 
![image](https://user-images.githubusercontent.com/1203788/60333806-525a9100-99dd-11e9-9a2b-2aa01c52d694.png)

**Comment by dante2130** [comment]
Request from Postman:

<img width="1165" alt="Screenshot 2019-06-28 at 12 47 54" src="https://user-images.githubusercontent.com/5721238/60334073-4e118200-99a3-11e9-8e72-fc9af63ebeb5.png">
